#pragma once
enum typeIO{
		NEUTRAL,
		FILEIOCREATE,
		FILEIOCLEANUP,
		FILEIOCLOSE,
		FILEIOFLUSH,
		FILEIOREAD,
		FILEIOWRITE,
		FILEIOSETINFO,
		FILEIOQUERYINFO,
		FILEIOFSCTL,
		FILEIODELETE,
		FILEIORENAME,
		FILEIODIRENUM,
		FILEIODIRNOTIFY,
		FILEIOOPEND
};